### ISSUE TITLE
Yaml variable substitution Azure pipeline

### ISSUE THREAD

**Issue by svrooij** [microsoft/variable-substitution#18]
Currently the Azure pipelines only support JSON and xml variable substitution. Yaml variable substitution would be a great addition.

**Comment by aksm-ms** [comment]
@N-Usha Can you please take a look at this?

**Comment by N-Usha** [comment]
@svrooij - Can you please clarify if your ask for YAML is in Azure Pipelines? If so, can you please raise the request here: https://github.com/microsoft/azure-pipelines-tasks/issues

**Comment by svrooij** [comment]
@N-Usha This is exactly what I'm trying to accomplish, created an issue in the other tracker.
