### ISSUE TITLE
Using this action changes timestamp format in the yaml file

### ISSUE THREAD

**Issue by RamMotaparthy-Zoetis** [microsoft/variable-substitution#20]
When this action is used to change a key in the yaml file, it changes other settings which have timestamps even thought the timestamps are not being touched by the action.

config.yaml:
`cco_start_date: 2021-02-08 15:04:50.825709`
`execution_date: 2021-02-11 15:04:50.825709`
`use_sample: false`

In the workflow.yaml, if we use 

`    - uses: microsoft/variable-substitution@v1 `
 `     name: Toggle Sample Run in the config.yaml`
`      with:`
`          files: '${{ env.CUSTOM_WORKSPACE }}/src/config.yaml'`
 `     env:`
  `        run_settings.use_sample: true`

the value of _use_sample_ will be changed to _true_, but also the in the **output** above timestamps will be changed to 
`cco_start_date: 2021-02-08T15:18:20.925Z`
`execution_date: 2021-02-11T15:18:20.925Z`
`use_sample: true`

**Expected behavior:**
All the other values should remain as-is, except for the substituted values.

**Comment by AmrutaKawade** [comment]
@RamMotaparthy-Zoetis can you given sample repo with repro of this issue?

**Comment by neerajram** [comment]
@AmrutaKawade Checkout this repo: https://github.com/neerajram/MS-variable-substitution-test

Actual config file: https://github.com/neerajram/MS-variable-substitution-test/blob/main/config/config.yaml
Workflow file: https://github.com/neerajram/MS-variable-substitution-test/blob/main/.github/workflows/var_replacement.yaml
The workflow updates the value of `use_sample` in the config, using the action. 

The config after the update can be found here: 
https://github.com/neerajram/MS-variable-substitution-test/runs/2042345882?check_suite_focus=true#step:4:4

As you can see, the timestamps are changed. 
Let me know if you need anything else.

**Comment by AmrutaKawade** [comment]
@neerajram thanks for sample repo.
But from your run I see that value is same but in different format unlike first example by @RamMotaparthy-Zoetis where value itself had changed.

https://github.com/neerajram/MS-variable-substitution-test/blob/3b9ba283bb48cd0ea56f47ee20528a9f0911695c/config/config.yaml#L2

![image](https://user-images.githubusercontent.com/65217380/110281439-c054b980-8002-11eb-9184-b8a895f2ddfa.png)

![image](https://user-images.githubusercontent.com/65217380/110281466-cd71a880-8002-11eb-9a4d-50615f9efc9c.png)

if format is the issue can you try adding dates in qoutes.

**Comment by neerajram** [comment]
@AmrutaKawade  When using quotes it is working fine, thanks
