### ISSUE TITLE
Failed to apply variable substitution

### ISSUE THREAD

**Issue by tomkerkhove** [microsoft/variable-substitution#34]
I have a workflow that [failed](https://github.com/azure-deprecation/infrastructure/runs/3535090863?check_suite_focus=true) with "Failed to apply variable substitution".

Is there a way to understand why? Is it because I use "." in the variables?

**Comment by luizmazuroski** [comment]
Your link is dead, which makes it hard for anybody to help you. What type of file you were using, json, yaml, xml? What is it's structure, what are your environment variables named, etc.

Anyway, I found out while stumbling upon an issue myself, that apparently it is possible to have more detailed debug messages from this action like so: https://github.com/actions/toolkit/blob/main/docs/action-debugging.md

Also, if you have no choice, like I didn't, you can have a look at the action source code here:
https://github.com/microsoft/variable-substitution

**Comment by tomkerkhove** [comment]
It's been a while so I'll just close the issue - Sorry for the inconvenience.
