### ISSUE TITLE
Only web.config XML files are supported :(

### ISSUE THREAD

**Issue by luizmazuroski** [microsoft/variable-substitution#35]
Only certain tags of xml are currently supported.

File https://github.com/microsoft/variable-substitution/blob/master/lib/operations/xmlVariableSubstitution.js
lists these specific tags:
const tags = ["applicationSettings", "appSettings", "connectionStrings", "configSections"];

If I want to replace variables inside any other xml file that is not a web.config, I'm not able to, and the error message is not helpful at all.
Please at least improve the documentation or error message, so that other users to not spend their time having to look at the action source code to figure out what is going on...

**Comment by BALAGA-GAYATRI** [comment]
@luizmazuroski Yes, currently only these tags can only be substituted in the XML. We have updated our [readme]( https://github.com/microsoft/variable-substitution#github-action-for-substituting-variables-in-parameterized-files-) with the same. Closing this issue.
