### ISSUE TITLE
Bug: Missing Replacement Action

### ISSUE THREAD

**Issue by Omzig** [microsoft/variable-substitution#43]
the microsoft doc will need to be updated or deleted if this action is not updated or replace. https://learn.microsoft.com/en-us/azure/developer/github/github-variable-substitution

Please consider making v2 of this action so that we can keep using it. 

I really do not want to fork it and keep a backup of this very useful action that we use in who knows how many repo's.

**Comment by sandrochristiaan** [comment]
Yes I agree, can we expect an update of this Action?

I get this message in workflow annotations: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

@N-Usha Is this action still 'live' or is it deprecated?

**Comment by N-Usha** [comment]
Thanks for reaching out folks. 
As stated in the [deprecation notice](https://github.com/microsoft/variable-substitution#deprecation-notice), 
This Action will not get any more investments into it and we plan to archive the repo very soon. However , all the existing & new workflows that use it will continue to work. Hope that helps to clarify. Thanks!

**Comment by Omzig** [comment]
> Thanks for reaching out folks. As stated in the [deprecation notice](https://github.com/microsoft/variable-substitution#deprecation-notice), This Action will not get any more investments into it and we plan to archive the repo very soon. However , all the existing & new workflows that use it will continue to work. Hope that helps to clarify. Thanks!

@N-Usha, something has to replace it... Do we know what that is? Or do we have to fork it and create a copy of it before it is lost?

**Comment by Omzig** [comment]
> Yes I agree, can we expect an update of this Action?
> 
> I get this message in workflow annotations: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> 
> @N-Usha Is this action still 'live' or is it deprecated?

It looks like someone in the community is going to have to pick up the torch since Microsoft see's no value in this action.

**Comment by N-Usha** [comment]
@Omzig - Unfortunately, there is no replacement planned for this. However as mentioned earlier, [Action repo](https://github.com/microsoft/variable-substitution) will be archived but will continue to work fine if used in Action workflows as-is. 
If you wish to invest further and create a more advanced version of the action, request you to create a new community action. Hope that clarifies. Thanks!
